SMA_long = 600
SMA_short = 50
BULL_RSI = 6
BULL_RSI_high = 45
BULL_RSI_low = 43
IDLE_RSI = 21
IDLE_RSI_high = 67
IDLE_RSI_low = 23
BEAR_RSI = 7
BEAR_RSI_high = 50
BEAR_RSI_low = 28
ROC = 7
ROC_lvl = 0