# BEST BTC/USD 2018-07-05 TO "2018-09-06 - 43"% 
#SMA_long = 600
#SMA_short = 110
#BULL_RSI = 11
#BULL_RSI_high = 60
#BULL_RSI_low = 10
#BEAR_RSI = 31
#BEAR_RSI_high = 80
#BEAR_RSI_low = 40
# AVERAGE OF FIVE BEST BTC/USD 2018-07-05 TO "2018-09-06 - 38"% 
SMA_long = 880
SMA_short = 106
BULL_RSI = 17
BULL_RSI_high = 62
BULL_RSI_low = 12
BEAR_RSI = 21
BEAR_RSI_high = 86
BEAR_RSI_low = 44
# BEST BTC/USD 2018-08-29 TO "2018-09-06 - 2"% 
#SMA_long = 500
#SMA_short = 100
#BULL_RSI = 20
#BULL_RSI_high = 60
#BULL_RSI_low = 8
#BEAR_RSI = 15
#BEAR_RSI_high = 90
#BEAR_RSI_low = 41

# BEST ETH/USD 2018-08-05 TO "2018-09-06 - 22"% 
#SMA_long = 200
#SMA_short = 50
#BULL_RSI = 21
#BULL_RSI_high = 50
#BULL_RSI_low = 20
#BEAR_RSI = 11
#BEAR_RSI_high = 70
#BEAR_RSI_low = 10